### ISSUE TITLE
supply exhaust outgoing outside

### ISSUE THREAD

**Issue by VincentSC** [coolchip/node-comfoair#11]
Zehnder talks about intake, exhaust, supply and extract. Or extract, supply, incoming and outgoing.

This library uses supply, exhaust, outgoing and outside.

![intake-exhaust-supply-extract](https://user-images.githubusercontent.com/5090382/120239403-7fb1b880-c25e-11eb-8d8c-f1282f01a7a6.png)

![image](https://user-images.githubusercontent.com/5090382/120240148-2a76a680-c260-11eb-9814-5f247a943423.png)

This is my guess how it translates:
- `outside` = intake / incoming
- `supply` = supply 
- `exhaust` = exhaust / outgoing
- `outgoing` = extract

Or....

- `outside` = intake / incoming
- `supply` = supply 
- `exhaust` = extract
- `outgoing` = exhaust / outgoing

Based on my current experiments on adiabatic cooling, I guess the second one is the correct one.

I leave it here for somebody who is also searching for translation between the different terms used.

Personally I'd prefer `extract` and `intake`/`incoming` are used, even if that is a breaking change. Now it's fizzyfuzzy

**Comment by VincentSC** [comment]
Looking at the outputs of `GetVentialtionLevels` and `getFanState` I'm thinking that exhaust and outgoing are mixed here. Zehnder mixes these two words, but in the library exhaust is actually extract and that makes it problematic

**Comment by coolchip** [comment]
Hello. Thank your very much for this issue. Do you want to create an pull request for this?

**Comment by coolchip** [comment]
Also added to README
