### ISSUE TITLE
Wrong parameter order for "setVentilationLevel"

### ISSUE THREAD

**Issue by martin1ehm** [coolchip/node-comfoair#16]
The parameters for the setVentilationLevel command are in the wrong order. (Tested on ComfoAir G90-150HL).

The correct order for this device is. 

- exhaustAway
- exhaustLow
- exhaustMiddle
- supplyAway
- supplyLow
- supplyMiddle
- exhaustHigh
- supplyHigh

**Comment by coolchip** [comment]
Hello. Thank you very much for this issue. I've fixed it and will upload a new npm package the next time.
