### ISSUE TITLE
Question about connecting ComfoAir 350 with HA Add-On Node-Red

### ISSUE THREAD

**Issue by sofa74surfer** [coolchip/node-comfoair#17]
Question:

I have a ComfoAir 350 and a HA Installation with NodeRed. What do you think? Can I give this a try? 

Exsys EX-6030 - Serial Server Mini, Serial Ports 1 RS232:
https://www.distrelec.ch/de/serial-server-mini-serial-ports-rs232-exsys-ex-6030/p/12576045?trackQuery=&pos=1&origPos=1&origPageSize=50&track=true

As I read in the manuals, I should be able to connect it with socat and therefore perhaps works with your node-comfoair Integration.

**Comment by coolchip** [comment]
Might work. But you can also connect your ComfoAir with RS232 directly to your Home Automation Central (PC, Raspy...).

**Comment by sofa74surfer** [comment]
There is only a 16mm Cable Pipe, my HA has no serial port and is far away of Comfoair and I have a crimping tool for RJ45. So i thought, it's easier for me this way. 

But I now found this one:

https://www.get-console.com/shop/en/25-airconsole-mini-20

I buy it and post here, if it works.

**Comment by sofa74surfer** [comment]
Next step ... I had to send Airconsole back, but now I have USR W630. I have configured it, socat is running on HA Server and in HA, I can see the file /dev/ttyV0 
But for now, I struggle with basics in the example: https://flows.nodered.org/node/node-red-contrib-comfoair
What is behind the objects on the left an right of object Comfoair? At the moment, I only get the Message "TypeError: SerialPort is not a constructor", when I deploy. Package serialport is installed. When I add Object "Serial In" to the Workflow and define /dev/ttyV0 and deploy it, I get a green connected symbol under "Serial In" Object. 
I really do not see, what I missed in the documentation?

**Comment by sofa74surfer** [comment]
I found, that comfoair package on https://flows.nodered.org/node/node-red-contrib-comfoair is version 0.0.8 and I tried to tell Home Assistant Add-On Node-Red to take additional npm Package comfoair, but Node-Red does not want to see, that there is an upgrade to 1.0.5. Is it possible to bring package on flows.nodered.org to the new version?

**Comment by sofa74surfer** [comment]
last try ... I took your sample "get Firmware", changed it to /dev/ttyV0 and saved to smoke.js in root of installed comfoair and execute it with node: Same Result "SerialPort is not a constructor"

[core-ssh comfoair]$ node smoke.js
/config/node-red/node_modules/comfoair/ComfoairStream.js:14
        this.port = new SerialPort(options.port, {
                    ^

TypeError: SerialPort is not a constructor
    at new ComfoairStream (/config/node-red/node_modules/comfoair/ComfoairStream.js:14:21)
    at new Comfoair (/config/node-red/node_modules/comfoair/Comfoair.js:17:25)
    at Object.<anonymous> (/config/node-red/node_modules/comfoair/smoke.js:3:21)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.7.0
[core-ssh comfoair]$ 
 *1  [bash]

**Comment by sofa74surfer** [comment]
Could it be possible, I have a problem with the Serial cable? In the Box of USR W630 was only a female/female Cable. The USR W630 has a male port and Comfoair has a female Port. So I went to Galaxus und bought a Gender-Changer male/male.

**Comment by sofa74surfer** [comment]
I think it's time to close this. Now, I use a Raspy Zero with direkt Connection and Node Red on it. From HA, I communicate with Rest Calls to the Node Red.
